version: '3.9'
services:
  backend:
    image: 631595683567.dkr.ecr.eu-north-1.amazonaws.com/markorudovic/prva_app-backend:latest
    ports:
      - "8001:8000"
    restart: unless-stopped

  frontend:
    image: 631595683567.dkr.ecr.eu-north-1.amazonaws.com/markorudovic/prva_app-frontend:latest
    ports:
      - "81:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://backend:8000